# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
      - main
      - qa
      - develop
      - feature/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'MultiSystemApi.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'Restore NuGets'
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: 'build'
    arguments: '$(solution)'
- task: VSTest@2
  displayName: 'Running Tests'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*tests.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    diagnosticsEnabled: true
    codeCoverageEnabled: true
    platform: '$(buildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publishing'
  inputs:
    command: publish
    publishWebProjects: True
    projects: |
      Sources/NetCore6/*.csproj
      !**/*Tests*.csproj
    arguments: '--configuration $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)'
    modifyOutputPath: true

- task: PublishPipelineArtifact@1
  displayName: 'Creating Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'CreareAPI'